#! /usr/bin/perl -w

# $Id: convertData,v 1.4 2008-07-27 11:10:24 mschwarz Exp $
#
# This script will convert a filepro map and datafile
# to a MySQL table create and insert script.
#

use XML::Simple;
use DBI;
use FilePro::Data;

my $fph = FilePro::Data->new($ARGV[0]);

print XML::Simple::XMLout($fph);

## Okay. We've got the data. Now let's do something with it.

#$db = 
