#! /usr/bin/perl -w

# $Id: convertData,v 1.4 2008-07-27 11:10:24 mschwarz Exp $
#
# This script will convert a filepro map and datafile
# to a MySQL table create and insert script.
#

use XML::Simple;
use Data::Dumper;
use DBI;
use FilePro::Data;

print "Script begins...\n";

my $fph = FilePro::Data->new($ARGV[0]);

print "FilePro::Data object built...\n";

my $iterator;

$iterator = $fph->newIterator();

print "We have an iterator...\n";

my $row;

while ($row = $fph->getNextRowHash($iterator)) {
	print Data::Dumper->Dump([ $row ]);
}

print Data::Dumper->Dump([ $fph ]);



## Okay. We've got the data. Now let's do something with it.

#$db = 
