#! /usr/bin/perl -w

# $Id: convertData,v 1.4 2008-07-27 11:10:24 mschwarz Exp $
#
# This script will convert a filepro map and datafile
# to a MySQL table create and insert script.
#

use XML::Simple;
use Data::Dumper;
use DBI;
use FilePro::Data;

my $fph = FilePro::Data->new($ARGV[0]);

print Data::Dumper->Dump([ $fph ]);

print Data::Dumper->Dump([ $fph->getRowHash(1) ]);
print Data::Dumper->Dump([ $fph->getRowHash(2) ]);
print Data::Dumper->Dump([ $fph->getRowHash(3) ]);


## Okay. We've got the data. Now let's do something with it.

#$db = 
